from pathlib import Path
from radgram.core.radfile import RadProject
from radgram.audio.synthesis import render_progression, render_progression_with_instrument, write_wav
from radgram.catalog.db import Catalog

STYLE_PROGRESSIONS={
 'pop':['C','G','Am','F'], 'cinematic':['C','Am','F','G'], 'rock':['Em','C','G','D'], 'jazz':['Cmaj7','Dm','G7','Cmaj7']
}

def compose(title='Untitled', artist='Radgram AI', style='cinematic', progression=None, bpm=96, out_dir='exports/song'):
    chords = progression or STYLE_PROGRESSIONS.get(style, STYLE_PROGRESSIONS['cinematic'])
    project=RadProject(title=title, artist=artist, bpm=bpm, key=chords[0][0], style=style, chords=chords, lyrics='sam ple a di o', tabs='Generated from chords: '+ ' | '.join(chords))
    out=Path(out_dir); out.mkdir(parents=True, exist_ok=True)
    rad_path=out/f'{title.replace(" ","_").lower()}.rad'
    project.save(rad_path)
    samples=render_progression(chords,bpm)
    wav_path=out/'render.wav'
    write_wav(wav_path, samples)
    return project, wav_path

def compose_to_db(title='Untitled', artist='Radgram AI', album='RADGRAM Sessions', style='cinematic', progression=None, bpm=96, instrument='Piano', out_dir='exports/song', db='radgram.sqlite3'):
    chords = progression or STYLE_PROGRESSIONS.get(style, STYLE_PROGRESSIONS['cinematic'])
    out=Path(out_dir); out.mkdir(parents=True, exist_ok=True)
    project=RadProject(title=title, artist=artist, bpm=bpm, key=chords[0][0], style=style, chords=chords, lyrics='sam ple a di o', tabs='Generated from chords: '+ ' | '.join(chords))
    rad_path=out/f'{title.replace(" ","_").lower()}.rad'; project.save(rad_path)
    audio=render_progression_with_instrument(chords, instrument, db=db, bpm=bpm)
    wav_path=out/'render.wav'; write_wav(wav_path, audio)
    cat=Catalog(db)
    artist_id=cat.add_artist(artist, style=style)
    album_id=cat.add_album(artist_id, album, description='Generated by RADGRAM Maestro')
    track_id=cat.add_track(album_id, title, file_path=str(wav_path), rad_path=str(rad_path), author=artist)
    comp_id=cat.add_composition(title, artist_guid=artist_id, album_guid=album_id, bpm=bpm, song_key=chords[0][0], style=style, progression=chords, lyrics=project.lyrics, tabs=project.tabs, rad_text=rad_path.read_text(encoding='utf-8'))
    cat.add_composition_part(comp_id, 'Main Progression', instrument_name=instrument, chords=chords, audio_path=str(wav_path), tabs=project.tabs)
    return {'artist_guid':artist_id,'album_guid':album_id,'track_guid':track_id,'composition_guid':comp_id,'wav':str(wav_path),'rad':str(rad_path)}
